### ISSUE TITLE
Add functionality to scrape osusearch.com for map IDs

### ISSUE THREAD

**Issue by DeltaZero17** [jramseygreen/Simple-Osu-Bot-Framework#1]
It would be nice to have functionality to access and filter the beatmaps on the osu! database, such that one could play a selection of maps that fit around certain requirements.

**Comment by jramseygreen** [comment]
I will implement the functionality of accessing beatmaps using the osu!api https://github.com/ppy/osu-api/

**Comment by jramseygreen** [comment]
Actually looking into things further, I'm going to use the API from [chimu.moe](https://chimu.moe/docs) since it should be a bit simpler to implement and nicer to use for dmca'd maps and the like.

**Comment by jramseygreen** [comment]
Implemented a search method with [chimo.moe API](https://chimu.moe/docs), see [here](https://github.com/jramseygreen/Simple-Osu-Bot-Framework#searching-for-beatmaps).
